version: "3"

services:
  gateway:
    image: nginx:1.26-alpine
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
       dmz_net:
         ipv4_address: 192.168.200.10
       app_net:
         ipv4_address: 192.168.201.10

  backend:
    image: node:18-alpine
    container_name: backend
    working_dir: /app
    command: > 
      sh -c "npm install -g http-server && 
             echo '{\"status\": \"Connected to Secure DB\", \"ip\": \"Unknown\"}' > index.html && 
             http-server -p 3000"
    networks:
       app_net: 
        ipv4_address: 192.168.201.20
       data_net:
        ipv4_address: 192.168.202.20

  database:
    image: postgres:15-alpine
    container_name: db
    environment:
      - POSTGRES_PASS=strongpassword
    networks:
       data_net:
          ipv4_address: 192.168.202.10

networks:
  dmz_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24

  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.201.0/24
  
  data_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.202.0/24

  

    

